name: E2E on Chrome
on:
  push:
    branches:
      - 'master'
  pull_request:
jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    name: Build and test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: cypress-io/github-action@v5
        with:
          browser: chrome
          project: ./
          browser: chrome
          build: yarn build
          start: yarn start
          wait-on: "http://localhost:3000"
        env:
          DATABASE_URI: ${{ secrets.DATABASE_URI }}
          ASSIGN_ADMIN_ROLE_ON_SIGN_UP: ${{ secrets.ASSIGN_ADMIN_ROLE_ON_SIGN_UP }}
          NEXT_PUBLIC_AUTHING_APP_ID: ${{ secrets.NEXT_PUBLIC_AUTHING_APP_ID }}
          NEXT_PUBLIC_AUTHING_APP_HOST: ${{ secrets.NEXT_PUBLIC_AUTHING_APP_HOST }}
          AUTHING_USER_POOL_ID: ${{ secrets.AUTHING_USER_POOL_ID }}
          AUTHING_USER_POOL_SECRET: ${{ secrets.AUTHING_USER_POOL_SECRET }}
          TM_ENTERPRISE_ID: ${{ secrets.TM_ENTERPRISE_ID }}
          TM_APP_ID: ${{ secrets.TM_APP_ID }}
          TM_SECRET_ID: ${{ secrets.TM_SECRET_ID }}
          TM_SECRET_KEY: ${{ secrets.TM_SECRET_KEY }}
          TM_ADMIN_USER_ID: ${{ secrets.TM_ADMIN_USER_ID }}